config/routes.rb
Rails.application.routes.draw do
  root 'lifes#index'
  get 'contents/edit'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :lifes do
    resources :contents
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :life
end

app/models/life.rb
class Life < ApplicationRecord
    attr_accessor :remember_token
    has_many :contents, dependent: :destroy
    before_save {self.email = self.email.downcase}
    # https://railstutorial.jp/chapters/modeling_users?version=6.0#sec-format_validation
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true
    
    # 渡されたパスワード（文字列）のハッシュ値を返す
    # https://railstutorial.jp/chapters/basic_login?version=6.0#sec-testing_layout_changes
    def Life.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # ランダムなトークンを返す
    def Life.new_token
        SecureRandom.urlsafe_base64
    end
    
    # 永続セッションのためにユーザーをデータベースに記憶する
    def remember
        self.remember_token = Life.new_token
        update_attribute(:remember_digest, Life.digest(remember_token))
    end
    
    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # ユーザーのログイン情報を破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include LifesHelper
    include SessionsHelper
    protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :ensure_user
  before_action :set_user, only:[:edit, :update, :destroy]
  
  def create
    @content = Content.new
    if @content.update(content_params)
      redirect_to life_path(@life)
      flash[:notice] = "success!"
    else
      redirect_to life_path(@life)
      flash[:alert] = "Error!"
    end
  end
  
  def edit
  end
  
  def update
    if @content.update(content_params)
      redirect_to life_path(@life)
      flash[:notice] = "Success!"
    else
      render :edit
      flash[:alert] = "Error!"
    end
  end
  
  def destroy
    @content.destroy
    redirect_to life_path(@life)
    flash[:notice] = "Deleted!"
  end
  
  private
    def set_user
      @content = @life.contents.find(params[:id])
    end
    
    def ensure_user
      @life = Life.find(params[:life_id])
      if @life.id != @current_user
        flash[:alert] = 'ログインしてください'
        redirect_to login_path
      end
    end
    
    def content_params
      params.require(:content).permit(:year, :month, :date, :event, :life_id)
    end
end

app/controllers/lifes_controller.rb
class LifesController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :logged_in_life, only: [:edit, :update] 
  before_action :correct_life_logged_in, only: [:edit, :update]
  
  def index
    @lifes = Life.paginate(page: params[:page])
  end

  def show
    @the_age = get_life_age(@life)
  end

  def new
    @life = Life.new
  end
  
  def create
    life = Life.new(user_params)
    if life.save
      log_in life
      UserMailer.with(life: life).welcome_email.deliver_later
      flash[:notice] = "created!"
      redirect_to root_path
    else
      flash.now[:alert] = "creation error!"
      render :new
    end
  end

  def edit
  end
  
  def update
    if params[:life][:image]
      @life.image = "#{@life.id}.jpg"
      image = params[:life][:image]
      File.binwrite("public/user_images/#{@life.image}", image.read)
    end
    if @life.update(life_params)
      flash[:notice] = "update!"
      redirect_to @life
    else
      flash.now[:alert] = "update error!"
      render :edit
    end
  end
  
  private
    def set_user
      @life = Life.find(params[:id])
    end
    
    def user_params
      params.require(:life).permit(:name, :email, :password, :password_confirmation)
    end
    
    def life_params
      params.require(:life).permit(:name, :year, :month, :date, :introduce, :image)
    end
    
    # 何らかのユーザーがログインしているか確認
    def logged_in_life
      unless logged_in?
        store_location # フレンドリーフォワーディングへ向けてURLを記憶
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_life_logged_in
      @life = Life.find(params[:id])
      redirect_to(root_url) unless current_life?(@life)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    life = Life.find_by(email: params[:session][:email].downcase)
    if life && life.authenticate(params[:session][:password])
      log_in life
      params[:session][:remember_me] == '1' ? remember(life) : forget(life)
      flash[:notice] = "Success!"
      redirect_back_or life
    else
      flash.now[:alert] = "Error!"
      render :new
    end
  end
  
  def destroy
    log_out if logged_in?
    flash[:notice] = "logout!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # 現在のページのパスを返却する
    def current_page_path
        request.path_info
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/lifes_helper.rb
module LifesHelper
    include SessionsHelper
    
    # ユーザーのプロフィール画像を返却する
    def profile_image(life)
        life.image != nil ? life.image : "/user_images/default.jpg"
    end
    
    # 現在表示中のページのユーザーのidとログイン中のユーザーidがあってるか確認(showページでの編集ボタンなどの表示確認用)
    def match_correct_life?(life)
        current_user && life.id == current_user.id
    end
    
    # ユーザーの年齢を返す
    def get_life_age(life)
        # lifeモデルのyear, month, dateのいずれもnilでない場合に実行
        if !life.year.nil? && !life.month.nil? && !life.date.nil?
            Time.zone = "Asia/Tokyo"
            # 現在時刻のyyyymmdd
            fomatted_time = Time.zone.now.to_formatted_s(:number).slice!(0...8)
            # 現在の年/月/日
            current_year = fomatted_time.slice!(0...4).to_i
            current_month = fomatted_time.slice!(0...2).to_i
            current_date = fomatted_time.slice!(0...2).to_i
            # 今年にthe_age歳になるので、月日によって条件分岐
            the_age = current_year - life.year
            if life.month > current_month
                the_age -= 1
            elsif life.month == current_month
                the_age -= 1 if life.date > current_date
            end
            return the_age
        else
            return false
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 特定のユーザーでログインする
    def log_in(life)
        session[:user_id] = life.id
    end
    
    # ユーザーのセッションを永続的にする
    def remember(life)
        life.remember
        cookies.permanent.signed[:user_id] = life.id
        cookies.permanent[:remember_token] = life.remember_token
    end
    
    # 現在ログイン中のユーザーを返す（いる場合）
    def current_user
        # セッション変数に値がある場合に@current_userの値を返す
        if (user_id = session[:user_id])
            @current_user ||= Life.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            life = Life.find_by(id: user_id)
            if life && life.authenticated?(cookies[:remember_token])
                log_in life
                @current_user = life
            end
        end
    end
    
    # 渡されたユーザーがカレントユーザーであればtrueを返す
    def current_life?(life)
        life && life == current_user
    end
    
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    def logged_in?
        !current_user.nil?
    end
    
    # 永続的セッションを破棄する
    def forget(life)
        life.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    # 現在のユーザーをログアウトする
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
    # 記憶したURL（もしくはデフォルト値）にリダイレクト
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    # アクセスしようとしたURLを覚えておく
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/views/contents/edit.html.erb
<div>
    <h2>Update your event</h2>
    <%= render "layouts/content-form" %>
</div>

app/views/layouts/_content-form.html.erb
<!--人生イベントの登録&編集用フォーム-->
<h3>Addition</h3>
<!--https://qiita.com/kiddikn/items/6df1770ce6f31533d654-->
<%= form_with model: [@life, Content.new], local: true do |f| %>
    <%= f.hidden_field :life_id, { value: @life.id } %>
    <div class="form-group">
        <label>Year</label>
        <%= f.number_field :year, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Month</label>
        <%= f.number_field :month, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Date</label>
        <%= f.number_field :date, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Event</label>
        <%= f.text_area :event, class: "form-control" %>
    </div>
    <div class="text-center">
        <%= f.submit "登録する", class: "btn btn-primary btn-wide" %>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="text-primary p-2 position-fixed bg-white rounded border border-info flash-message">
    <p>
      <%= message %>
    </p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="bg-primary d-flex justify-content-between align-items-center">
  <h2 class="p-2">
    <%= link_to "Search your life", root_path, class: "text-white text-decoration-none site-title" %>
  </h2>
  <nav>
    <ul class="pr-5 mb-0 d-flex align-items-center">
      <% if logged_in? %>
        <div>
          <%= link_to "マイページ", life_path(@current_user), class: "text-white" %>
        </div>
        <div class="ml-2">
          <%= link_to "ログアウト", logout_path, class: "text-white", method: :delete %>
        </div>
      <% else %>
        <!--ログインページではログインのリンクを非表示に-->
        <% if current_page_path != login_path %>
          <p class="mb-0">
            <%= link_to "ログイン", login_path, class: "text-white" %>
          </p>
        <% end %>
        <!--新規登録ページでは新規登録のリンクを非表示に-->
        <% if current_page_path != new_life_path %>
          <p class="ml-4 mb-0">
            <%= link_to "新規登録", new_life_path, class: "text-white" %>
          </p>
        <% end %>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
  <head>
    <title><%= yield(:title) %> | Search your life</title>
    <meta name="description" content="'Search your life' is a SaaS To find an example of your life." />
    <!--<link rel="icon" href="/favicon.ico" />-->
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Search your life"/>
    <meta property="og:description" content="'Search your life' is a SaaS To find an example of your life."/>
    <meta property="og:url" content="https://search-your-life.herokuapp.com/"/>
    <meta property="og:site_name" content="Search your life"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:site" content="Search your life"/>
    <meta name="twitter:title" content="Search your life"/>
    <meta name="twitter:description" content="'Search your life' is a SaaS To find an example of your life."/>
    <meta name="twitter:image" content="/ogp.png"/>
    <meta name="twitter:url" content="https://search-your-life.herokuapp.com/"/>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/header' %>
    <div class="container mt-5 pb-5">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/lifes/_basic-form.html.erb
 <!--名前、生年月日、自己紹介、アイコンの設定フォーム-->
 <%= form_with(model: @life, multipart: true, local: true) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <div class="form-group">
        <%= f.label :name  %>
        <%= f.text_field :name, value: @life.name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :year %>
        <%= f.number_field :year, value: @life.year, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :month %>
        <%= f.number_field :month, value: @life.month, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :date %>
        <%= f.number_field :date, value: @life.date, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :introduce %>
        <%= f.text_area :introduce, value: @life.introduce, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, value: @life.image, class: "form-control" %>
    </div>
    <div class="text-center">
        <%= f.submit "登録する", class: "btn btn-primary btn-wide" %>
    </div>
<% end %>

app/views/lifes/_basic-infomation.html.erb
<!--名前、生年月日、自己紹介の基本情報の出力-->
<div class="d-flex w-100 align-items-start">
    <div class="mr-4">
        <img class="profile-image-detail" src="<%= profile_image(@life) %>">
    </div>
    <div>
        <h2>
            <%= @life.name %>
        </h2>
        <div class="d-inline-block mb-2 border-bottom border-dark">
            <span><%= @life.year %>年</span>
            <span><%= @life.month %>月</span>
            <span><%= @life.date %>日</span>
            <span>生まれ</span>
            <% if @the_age %>
                <span>（現在<%= @the_age %>歳）</span>
            <% end %>
        </div>
        <p>
            <%= @life.introduce %>
        </p>
    </div>
</div>

app/views/lifes/_content-show.html.erb
<!--人生登録イベントの表示&編集-->
<h3>Events</h3>
<table class="table table-striped">
    <% if @life.contents.any? %>
        <thead class="thead-light">
            <tr>
                <td>Year</td>
                <td>Month</td>
                <td>Date</td>
                <td>Event</td>
                <!--現在ログインしているユーザーと訪問している詳細ページのidを比較-->
                <% if @life.id == @current_user %>
                    <td></td>
                    <td></td>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @life.contents.each do |content| %>
            <tr>
                <td>
                    <%= content.year %>
                </td>
                <td>
                    <%= content.month %>
                </td>
                <td>
                    <%= content.date %>
                </td>
                <td>
                    <%= content.event %>
                </td>
                <!--現在ログインしているユーザーと訪問している詳細ページのidを比較-->
                <% if @life.id == @current_user %>
                    <td>
                        <%= link_to "Edit", edit_life_content_path(@life, content), class: "btn btn-primary" %>
                    </td>
                    <td>
                        <%= link_to "Delete", life_content_path(@life, content), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
                    </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    <% else %>
        <p>No Events</p>
    <% end %>
</table>

app/views/lifes/edit.html.erb
<% provide(:title, "Edit") %>
<div class="mt-5">
 <%= render "basic-form" %>
</div>

app/views/lifes/index.html.erb
<% provide(:title, "Home") %>

<%= will_paginate %>

<div class="card-columns index-column my-3">
    <% @lifes.each do |life| %>
        <% if life.name %>
            <%= link_to life_path(life), class: "card" do %>
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <div class="mr-3">
                            <img class="profile-image" src="<%= profile_image(life) %>">
                        </div>
                        <div>
                            <h3><%= life.name %></h3>
                            <p class="adjust-intro"><%= life.introduce %></p>
                            <p>メール：<%= life.email %></p>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>

<%= will_paginate %>

app/views/lifes/login_form.html.erb
<% provide(:title, "Login") %>
<div>
    <h2 class="mb-5 text-center">ログイン</h2>
    <div class="w-50 mx-auto">
        <%= form_with url: "/login" do |f|%>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="text-center">
                <%= f.submit "ログイン", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/lifes/new.html.erb
<% provide(:title, "New") %>
<div>
    <h2 class="mb-5 text-center">新規登録</h2>
    <div class="w-50 mx-auto">
        <%= form_with(model: @life, url: lifes_path, local: true) do |f| %>
            <div class="form-group">
                <%= f.label :name, "名前" %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :email, "メールアドレス" %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password, "パスワード" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation, "パスワード確認" %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <div class="text-center">
                <%= f.submit "登録", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/lifes/show.html.erb
<% provide(:title, "Show") %>
<div>
    <%= render "basic-infomation" %>
    <% if match_correct_life?(@life) %>
        <div class="mt-3 w-100">
            <%= link_to "編集する", edit_life_path, class: "btn btn-primary btn-wide" %>
        </div>
    <% end %>
    <div class="mt-5">
        <%= render "content-show" %>
    </div>
    <% if match_correct_life?(@life) %>
        <div class="mt-5">
            <%= render "layouts/content-form" %>
        </div>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @life.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            エラーが<%= @life.errors.count %>個あります。
        </div>
        <ul>
            <% @life.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>